<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

/**
 * Upgrades openveo block depending on actual version.
 *
 * For version older than 2016021500 :
 * Media ids generated by OpenVeo can contains characters, not only digits, thus the table field "videoid" needs to
 * store Strings and not Integers.
 *
 * @package block_openveo_videos
 * @copyright 2018 Veo-labs
 * @license http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
function xmldb_block_openveo_videos_upgrade($oldversion){
    global $DB;
    $dbman = $DB->get_manager();

    /// Change the type of the field "videoid" from Integer to String
    if($oldversion < 2016021500){
        $table = new xmldb_table('block_openveo_videos');
        $field = new xmldb_field('videoid', XMLDB_TYPE_CHAR, '20', null, XMLDB_NOTNULL, null, null, null);
        $dbman->change_field_type($table, $field);
        upgrade_block_savepoint(true, 2016021500, 'openveo_videos');
    }

    /// Remove config wsserverhost, wsserverport, serverhost, serverport and automatically set the new config wsserverurl and serverurl
    if($oldversion < 2017061400){
      $wsserverhost = get_config('openveo_videos', 'wsserverhost');
      $wsserverport = get_config('openveo_videos', 'wsserverport');
      $serverhost = get_config('openveo_videos', 'serverhost');
      $serverport = get_config('openveo_videos', 'serverport');

      if(!empty($wsserverhost) && !empty($wsserverport))
        set_config('wsserverurl', 'http://'.$wsserverhost.':'.$wsserverport, 'openveo_videos');

      if(!empty($serverhost) && !empty($serverport))
        set_config('serverurl', 'http://'.$serverhost.':'.$serverport, 'openveo_videos');

      unset_config('wsserverhost', 'openveo_videos');
      unset_config('wsserverport', 'openveo_videos');
      unset_config('serverhost', 'openveo_videos');
      unset_config('serverport', 'openveo_videos');
    }

    // Remove settings which now belongs to OpenVeo Moodle API plugin.
    if ($oldversion < 2018101100) {
        unset_config('serverurl', 'openveo_videos');
        unset_config('wsserverurl', 'openveo_videos');
        unset_config('wsservercertificate', 'openveo_videos');
        unset_config('wsclientid', 'openveo_videos');
        unset_config('wsclientsecret', 'openveo_videos');
    }

    return true;
}
