<?php
// This file is part of OpenVeo - http://www.veo-labs.com/suite-logicielle-openveo
//
// TODO : Add License information here

/**
 * Upgrades openveo block depending on actual version.
 *
 * For version older than 2016021500 :
 * Media ids generated by OpenVeo can contains characters, not only digits, thus the table field "videoid" needs to
 * store Strings and not Integers.
 *
 * @package block_openveo_videos
 * @copyright 2015, veo-labs <info@veo-labs.com>
 * @license TODO
 */
function xmldb_block_openveo_videos_upgrade($oldversion) {
    global $DB;
    $dbman = $DB->get_manager();

    /// Change the type of the field "videoid" from Integer to String
    if ($oldversion < 2016021500) {
        $table = new xmldb_table('block_openveo_videos');
        $field = new xmldb_field('videoid', XMLDB_TYPE_CHAR, '20', null, XMLDB_NOTNULL, null, null, null);
        $dbman->change_field_type($table, $field);
        upgrade_block_savepoint(true, 2016021500, 'openveo_videos');
    }

    return true;
}